name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  DEFAULT_EMAILS: '["email1@example.com", "email2@example.com", "email3@example.com"]'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --extra dev

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Run tests with coverage
        run: |
          if [ -d "tests" ]; then
            echo "Running tests..."
            uv run pytest --cov=src --cov-report=xml --cov-report=html
          else
            echo "No tests found, skipping..."
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        with:
            args: >
              -Dsonar.projectKey=josdem_py-vetlog-calendar
              -Dsonar.organization=josdem-io